// ─────────────────────────────────────────────────────────────
// VALUE OBJECTS
// ─────────────────────────────────────────────────────────────

export type TagSource = "manual" | "llm" | "heuristic";

export interface TagProps {
  id?: number;
  name: string;
  source: TagSource;
  confidence?: number | null; // 0–1, only when source = "llm"
  createdAt?: Date;
}

// ─────────────────────────────────────────────────────────────
// ENTITY
// Represents a label that can be manually or automatically
// applied to a snippet. Tags are case-insensitive and normalized.
// ─────────────────────────────────────────────────────────────

export class TagEntity {
  readonly id?: number;
  readonly name: string;           // always lowercase-normalized
  readonly source: TagSource;
  readonly confidence: number | null;
  readonly createdAt: Date;

  private constructor(props: TagProps) {
    this.id = props.id;
    this.name = TagEntity.normalize(props.name);
    this.source = props.source;
    this.confidence = props.confidence ?? null;
    this.createdAt = props.createdAt ?? new Date();
  }

  // ── Factory ──────────────────────────────────────────────────

  static create(props: TagProps): TagEntity {
    const normalized = TagEntity.normalize(props.name);
    if (normalized.length === 0) {
      throw new Error("TagEntity: name must not be empty after normalization");
    }
    if (normalized.length > 64) {
      throw new Error("TagEntity: name must not exceed 64 characters");
    }
    if (!/^[a-z0-9._-]+$/.test(normalized)) {
      throw new Error(
        `TagEntity: name "${normalized}" contains invalid characters (allowed: a-z 0-9 . _ -)`
      );
    }
    if (props.confidence !== undefined && props.confidence !== null) {
      if (props.confidence < 0 || props.confidence > 1) {
        throw new Error("TagEntity: confidence must be between 0 and 1");
      }
    }
    return new TagEntity({ ...props, name: normalized });
  }

  static reconstitute(props: Required<TagProps>): TagEntity {
    return new TagEntity(props);
  }

  // ── Business rules ───────────────────────────────────────────

  static normalize(name: string): string {
    return name.toLowerCase().trim().replace(/\s+/g, "-");
  }

  isAutoGenerated(): boolean {
    return this.source === "llm" || this.source === "heuristic";
  }

  isHighConfidence(): boolean {
    if (this.source === "manual") return true;
    return (this.confidence ?? 0) >= 0.8;
  }

  /** Two tags are equivalent if their normalized names match */
  equals(other: TagEntity): boolean {
    return this.name === other.name;
  }
}
